[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "bcrypt>=4.2.1",
    "flask>=3.1.0",
    "flask-cors>=5.0.0",
]
